version: 2
jobs:
  build:
    parallelism: 1
    docker:
      # Bump cache key version below when changing elixir version
      - image: cimg/elixir:1.13.0
        environment:
          MIX_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_DB: survey_api_test
          POSTGRES_PASSWORD:
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: survey_api_test
          POSTGRES_PASSWORD:
    # resource_class: medium+
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run:
          command: mix compile
          environment:
            MIX_ENV: test
      - save_cache:
          key: v4-dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - restore_cache:
          keys:
            - v4-plt-cache-{{ checksum "mix.lock" }}
            - v4-plt-cache
      - save_cache:
          key: v4-plt-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - ~/.mix
      - run: mix credo
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix test
