version: 2
jobs:
  build:
    parallelism: 1
    docker:
      # Bump cache key version below when changing elixir version
      - image: cimg/elixir:1.15
        environment:
          MIX_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_DB: survey_api_test
          POSTGRES_PASSWORD: null
      - image: cimg/postgres:16.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: survey_api_test
          POSTGRES_PASSWORD: null
    # resource_class: medium+
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run:
          command: mix compile
          environment:
            MIX_ENV: test
      - save_cache:
          key: v4-dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - run: mix test
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
